# google_forms_integration.py
import os
import json
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError
from google.oauth2.credentials import Credentials
from google.auth.transport.requests import Request
import uuid # For generating unique IDs for questions
import google.generativeai as google_ai # NEW: Import Google Generative AI

# Placeholder for speak function if this file is run standalone for testing
def speak_placeholder(text):
    print(f"Forms Integration: {text}")

# NEW: Configure Gemini AI for this module
# It's assumed that apikey.py provides GEN_AI_API_KEY
try:
    from apikey import api_data as GEN_AI_API_KEY
except ImportError:
    print("Error: apikey.py not found or GEN_AI_API_KEY not defined. Using placeholder.")
    GEN_AI_API_KEY = "YOUR_GEMINI_API_KEY" # Replace with your actual Gemini API Key

try:
    google_ai.configure(api_key=GEN_AI_API_KEY)
except Exception as e:
    print(f"❌ Error configuring Gemini API in google_forms_integration.py: {e}. Please check your GEN_AI_API_KEY.")


# Removed get_google_credentials_for_forms and SCOPES definitions
# These will now be passed from main.py to ensure unified authentication.


def generate_options_with_gemini(form_topic: str, question_text: str, speak_func=None):
    """
    Uses Gemini to generate options for a given question, especially for rating-like questions.
    """
    if speak_func is None:
        speak_func = speak_placeholder

    prompt = f"""
    You are an AI assistant specialized in creating options for survey questions.
    Given the form's overall topic and a specific question, generate a list of 4-5 relevant options.
    Focus on common rating scales (e.g., Excellent to Poor, Strongly Agree to Strongly Disagree) if the question implies it.
    If the question is about preferences, provide diverse choices.

    Form Topic: "{form_topic}"
    Question: "{question_text}"

    Provide ONLY a JSON array of strings for the options.
    Example: ["Excellent", "Very Good", "Good", "Not Good"]
    Example: ["Strongly Agree", "Agree", "Neutral", "Disagree", "Strongly Disagree"]
    Example: ["Option A", "Option B", "Option C"]
    """
    print(f"🧠 Asking Gemini to generate options for: '{question_text}' (Topic: '{form_topic}')")
    speak_func(f"Generating options for the question: '{question_text}'.")
    try:
        model = google_ai.GenerativeModel("gemini-2.5-flash")
        response = model.generate_content(prompt)
        
        json_string = response.text.strip()
        if json_string.startswith("```json"):
            json_string = json_string[7:].strip()
        if json_string.endswith("```"):
            json_string = json_string[:-3].strip()

        options_list = json.loads(json_string)
        if not isinstance(options_list, list) or not all(isinstance(item, str) for item in options_list):
            raise ValueError("Gemini response for options is not a list of strings.")

        print(f"✅ Gemini generated options: {options_list}")
        return options_list
    except json.JSONDecodeError as e:
        print(f"❌ Error parsing JSON from Gemini for options: {e}. Response: {response.text}")
        speak_func("I had trouble understanding the options generated by AI.")
        return []
    except Exception as e:
        print(f"❌ An unexpected error occurred with Gemini during option generation: {e}")
        speak_func("I encountered an issue while generating options with AI.")
        return []


def create_google_form(form_title: str, form_description: str, questions_data: list, speak_func=None, form_topic: str = "", get_credentials_func=None, all_scopes=None):
    """
    Creates a new Google Form with the given title, description, and questions.
    Args:
        form_title (str): The title of the new Google Form.
        form_description (str): The description of the new Google Form.
        questions_data (list): A list of dictionaries, each representing a question.
                               Example: [{"question_text": "Name?", "type": "TEXT"},
                                         {"question_text": "Favorite color?", "type": "MULTIPLE_CHOICE", "options": ["Red", "Blue"]}]
        speak_func (callable, optional): The Jarvis speak function to provide voice feedback.
        form_topic (str): The overall topic of the form, used for generating options.
        get_credentials_func (callable): The function from main.py to get Google credentials.
        all_scopes (list): The comprehensive list of scopes used by the main application.
    Returns:
        str: The URL of the created Google Form, or None if an error occurred.
    """
    if speak_func is None:
        speak_func = speak_placeholder # Use placeholder if not provided
    if get_credentials_func is None:
        speak_func("Authentication function not provided. Cannot create form.")
        print("❌ Authentication function not provided. Cannot create form.")
        return None

    # Use the provided get_credentials_func from main.py
    creds = get_credentials_func() 
    if not creds:
        speak_func("Failed to authenticate with Google Forms. Cannot create form.")
        print("❌ Failed to get Google Forms credentials. Cannot create form.")
        return None

    # Validate that the credentials cover the necessary Forms API scopes
    # This check is important because get_credentials_func might return creds
    # that don't have forms.body or forms.responses.readonly if those weren't requested
    # during the initial auth flow.
    required_forms_scopes = [
        'https://www.googleapis.com/auth/forms.body',
        'https://www.googleapis.com/auth/forms.responses.readonly'
    ]
    if not all(s in creds.scopes for s in required_forms_scopes):
        speak_func("Your current Google authentication does not cover the necessary Forms API permissions. Please re-authenticate Jarvis with all required permissions.")
        print("❌ Forms API scopes missing from authenticated credentials. Re-authentication with correct scopes is needed.")
        return None

    try:
        forms_service = build('forms', 'v1', credentials=creds)

        # 1. Create a new blank form with only the title
        new_form = {
            "info": {
                "title": form_title,
            }
        }
        create_response = forms_service.forms().create(body=new_form).execute()
        form_id = create_response.get('formId')
        form_url = create_response.get('responderUri') # This is the URL for users to fill out the form

        speak_func(f"Creating a new Google Form titled '{form_title}'.")
        print(f"✅ Created Google Form with ID: {form_id}")
        print(f"Form URL: {form_url}")

        # 2. Prepare batch update requests to add description and questions
        requests = []

        # Add request to update the form's description
        if form_description:
            requests.append({
                "updateFormInfo": {
                    "info": {
                        "description": form_description
                    },
                    "updateMask": "description" # Specify that only the description is being updated
                }
            })

        for i, q_data in enumerate(questions_data):
            question_text = q_data.get("question_text")
            question_type = q_data.get("type", "TEXT") # Default to TEXT if type is missing
            options = q_data.get("options")
            needs_ai_options = False
            if question_type in ["MULTIPLE_CHOICE", "CHECKBOX", "DROPDOWN"]:
                if not options or len(options) == 0:
                    needs_ai_options = True
                elif any(keyword in question_text.lower() for keyword in ["quality", "rating", "satisfaction", "feedback", "experience"]):
                    needs_ai_options = True
            if needs_ai_options:
                generated_options = generate_options_with_gemini(form_topic, question_text, speak_func)
                if generated_options:
                    options = generated_options
                else:
                    options = ["Yes", "No"] # Fallback if AI generation fails
            new_item_request = {
                "createItem": {
                    "item": {
                        "title": question_text,
                        "questionItem": {
                            "question": {
                                "required": False
                            }
                        }
                    },
                    "location": {
                        "index": i
                    }
                }
            }
            # Configure question type and options
            if question_type == "TEXT":
                new_item_request["createItem"]["item"]["questionItem"]["question"]["textQuestion"] = {
                    "paragraph": False
                }
            elif question_type == "PARAGRAPH_TEXT":
                new_item_request["createItem"]["item"]["questionItem"]["question"]["textQuestion"] = {
                    "paragraph": True
                }
            elif question_type == "MULTIPLE_CHOICE" and options:
                new_item_request["createItem"]["item"]["questionItem"]["question"]["choiceQuestion"] = {
                    "type": "RADIO",
                    "options": [{"value": opt} for opt in options]
                }
            elif question_type == "CHECKBOX" and options:
                new_item_request["createItem"]["item"]["questionItem"]["question"]["choiceQuestion"] = {
                    "type": "CHECKBOX",
                    "options": [{"value": opt} for opt in options]
                }
            elif question_type == "DROPDOWN" and options:
                new_item_request["createItem"]["item"]["questionItem"]["question"]["choiceQuestion"] = {
                    "type": "DROP_DOWN",
                    "options": [{"value": opt} for opt in options]
                }
            else:
                print(f"WARNING: Unsupported question type '{question_type}' or missing options for question '{question_text}'. Defaulting to TEXT.")
                new_item_request["createItem"]["item"]["questionItem"]["question"]["textQuestion"] = {
                    "paragraph": False
                }
            requests.append(new_item_request)
        if requests:
            batch_update_request = {"requests": requests}
            forms_service.forms().batchUpdate(formId=form_id, body=batch_update_request).execute()
            speak_func(f"Added {len(questions_data)} questions and description to the form.")
            print(f"✅ Added {len(questions_data)} questions and description to the form.")
        else:
            speak_func("No questions were generated or added to the form.")
            print("No questions to add to the form.")
        return form_url

    except HttpError as err:
        speak_func(f"An error occurred with the Google Forms API: {err.resp.status}. Please check permissions.")
        print(f"❌ Google Forms API Error: {err}")
        if err.resp.status == 400:
            print("Error 400: Bad Request. Check your request payload and question types/options.")
            print(f"Response: {err.content.decode('utf-8')}")
        elif err.resp.status == 403:
            print("Error 403: Permissions issue. Ensure Google Forms API is enabled and correct scopes are granted.")
        elif err.resp.status == 404:
            print("Error 404: Resource not found.")
        return None
    except Exception as e:
        speak_func(f"An unexpected error occurred while creating the Google Form: {e}")
        print(f"❌ An unexpected error occurred while interacting with Google Forms: {e}")
        return None
